name: Andrea Venuta - Thesis prototypes
markdown: kramdown
highlighter: pygments
collections:
  source:
    output: true
  js:
    output: true
baseurl: /thesis
exclude: ['src', 'LICENSE', 'README.md', 'npm-debug.log']
keep_files: ['build.js']
